

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - db_teacher:/var/lib/mysql
    networks:
      - net_teacher

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_HOST=db
    networks:
      - net_teacher
    ports:
      - "80:80"

  app:
    build:
      context: .
    restart: always
    depends_on:
      - db
    ports:
      - "8090:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - EUREKA=${EUREKA_SERVICES}
    networks:
      - net_teacher

volumes:
  db_teacher:

networks:
  net_teacher: